plugins {
    id 'java'
    id 'io.qameta.allure' version '2.12.0'
}

group = 'ru.netology'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

def junitVersion = '5.10.2'
def selenideVersion = '6.19.1'
def allureVersion = '2.25.0'

dependencies {
    testImplementation "org.junit.jupiter:junit-jupiter:$junitVersion"
    testImplementation "com.codeborne:selenide:$selenideVersion"

    testImplementation "io.qameta.allure:allure-selenide:$allureVersion"

    testImplementation 'com.github.javafaker:javafaker:1.0.2'

    testImplementation 'mysql:mysql-connector-java:8.0.33'
    testImplementation 'org.postgresql:postgresql:42.7.3'
    testImplementation 'org.awaitility:awaitility:4.2.2'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    useJUnitPlatform()

    systemProperty 'db.url', System.getProperty(
            'db.url',
            'jdbc:mysql://localhost:3306/app'
    )
    systemProperty 'db.user', System.getProperty('db.user', 'app')
    systemProperty 'db.password', System.getProperty('db.password', 'pass')
}